--USANDO LA BASE DE DATOS MASTER
USE MASTER
GO

IF EXISTS(SELECT NAME FROM SYS.DATABASES WHERE NAME='EMPRESA_LIBROS')
BEGIN
	DROP DATABASE EMPRESA_LIBROS
END
GO

CREATE DATABASE EMPRESA_LIBROS
GO

USE EMPRESA_LIBROS
GO

CREATE TABLE LIBROS(
LibroID INT,
Pagina INT,
Titulo VARCHAR(MAX),
Categoria VARCHAR(MAX)
)
GO

CREATE TABLE AUTOR(
AutorID INT,
Autor VARCHAR(150)
)
GO

CREATE TABLE LIBRO_AUTOR(
LibroID INT,
AutorID INT
)
GO

CREATE TABLE RESENIA(
ReseniaID INT,
Resenia VARCHAR(MAX)
)
GO

CREATE TABLE LIBRO_RESENIA(
LibroID INT,
ReseniaID INT
)
GO


SELECT * FROM LIBROS
GO
SELECT * FROM AUTOR
GO
SELECT * FROM LIBRO_AUTOR
GO
SELECT * FROM RESENIA
GO
SELECT * FROM LIBRO_RESENIA
GO


SELECT * FROM
LIBROS AS L INNER JOIN LIBRO_AUTOR AS LA ON L.LibroID=LA.LibroID
			INNER JOIN AUTOR AS A ON A.AutorID=LA.AutorID
			INNER JOIN LIBRO_RESENIA AS LR ON LR.LibroID=L.LibroID
			INNER JOIN RESENIA AS R ON R.ReseniaID = LR.ReseniaID
GO


SELECT L.Titulo, L.Categoria, A.Autor, R.Resenia
FROM
LIBROS AS L INNER JOIN LIBRO_AUTOR AS LA ON L.LibroID=LA.LibroID
			INNER JOIN AUTOR AS A ON A.AutorID=LA.AutorID
			INNER JOIN LIBRO_RESENIA AS LR ON LR.LibroID=L.LibroID
			INNER JOIN RESENIA AS R ON R.ReseniaID = LR.ReseniaID
GO
