----------- INSERTAR REGISTROS EN CUSTOMERS
CREATE PROCEDURE SP_InsertarClientes
AS
	IF EXISTS(
		SELECT CustomerID FROM BICICLETA.dbo.CLIENTES WHERE CustomerID COLLATE SQL_Latin1_General_CP1_CI_AS NOT IN (SELECT CustomerID FROM NORTHWND.dbo.Customers)
	)
	BEGIN
		INSERT INTO NORTHWND.dbo.Customers([CustomerID], [CompanyName], [ContactName], [ContactTitle], [Address], [City], [Region], [PostalCode], [Country], [Phone], [Fax])
		SELECT CustomerID, CompanyName, ContactName, ContactTitle, Address, City, Region, PostalCode, Country, Phone, Fax FROM BICICLETA.dbo.CLIENTES
		WHERE Fecha=CAST(CAST(YEAR(GETDATE()) AS VARCHAR(4)) + RIGHT('0'+CAST(MONTH(GETDATE()) AS VARCHAR(2)),2)+RIGHT('0'+CAST(DAY(GETDATE()) AS VARCHAR(2)),2) AS INT)

		PRINT 'SE INSERTARON REGISTROS EN LA TABLA CUSTOMERS DE NORTHWND'
	END ELSE
	BEGIN
		PRINT 'YA SE ENCUENTRAN REGISTRADOS LOS CLIENTES'
	END
	GO
GO

--CONSULTAS
SELECT * FROM NORTHWND.DBO.Customers
GO
SELECT * FROM BICICLETA.DBO.CLIENTES
GO


EXEC SP_InsertarClientes
GO



----------- INSERTAR REGISTROS EN ORDERS
CREATE PROCEDURE SP_IntertarOrdenes
AS
	IF EXISTS(
		SELECT CustomerID FROM BICICLETA.dbo.CLIENTES WHERE CustomerID COLLATE SQL_Latin1_General_CP1_CI_AS NOT IN (SELECT CustomerID FROM NORTHWND.dbo.Orders)
	)
	BEGIN
		INSERT INTO NORTHWND.dbo.Orders([CustomerID], [EmployeeID], [OrderDate], [RequiredDate], [ShippedDate], [ShipVia], [Freight], [ShipName], [ShipAddress], [ShipCity], [ShipRegion], [ShipPostalCode], [ShipCountry])
		SELECT CustomerID, EmployeeID, OrderDate, RequieredDate, ShippedDate, ShipVia, Freight, ShipName, ShipAddress, ShipCity, ShipRegion, ShipPostalCode, ShipCountry FROM BICICLETA.dbo.CLIENTES
		WHERE Fecha=CAST(CAST(YEAR(GETDATE()) AS VARCHAR(4)) + RIGHT('0'+CAST(MONTH(GETDATE()) AS VARCHAR(2)),2)+RIGHT('0'+CAST(DAY(GETDATE()) AS VARCHAR(2)),2) AS INT)

		PRINT 'SE INSERTARON REGISTROS EN LA TABLA ORDERS DE NORTHWND'
	END ELSE
	BEGIN
		PRINT 'YA SE ENCUENTRAN REGISTRADOS LOS PEDIDOS'
	END
	GO
GO

--CONSULTA
SELECT * FROM NORTHWND.DBO.Orders
GO
SELECT * FROM BICICLETA.DBO.CLIENTES
GO


EXECUTE SP_IntertarOrdenes
GO


----------- INSERTAR REGISTROS EN [ORDER DETAILS]
CREATE PROCEDURE SP_IntertarDetallesOrdenes
AS
	IF EXISTS(
		SELECT OrderID FROM NORTHWND.dbo.Orders WHERE OrderID NOT IN (SELECT OrderID FROM NORTHWND.dbo.[Order Details])
	)
	BEGIN
		INSERT INTO NORTHWND.dbo.[Order Details]([OrderID], [ProductID], [UnitPrice], [Quantity], [Discount])
		SELECT O.OrderID, C.ProductID, C.UnitPrice, C.Quantity, C.Discount
		FROM BICICLETA.DBO.CLIENTES AS C
		INNER JOIN NORTHWND.DBO.Customers AS N
		ON C.CustomerID COLLATE Modern_Spanish_CI_AS=N.CustomerID
		INNER JOIN NORTHWND.DBO.Orders AS O
		ON N.CustomerID=O.CustomerID
		WHERE C.Fecha=CAST(CAST(YEAR(GETDATE()) AS VARCHAR(4)) + RIGHT('0'+CAST(MONTH(GETDATE()) AS VARCHAR(2)),2)+RIGHT('0'+CAST(DAY(GETDATE()) AS VARCHAR(2)),2) AS INT)

		PRINT 'SE INSERTARON REGISTROS EN LA TABLA [ORDER DETAILS] DE NORTHWND'
	END ELSE
	BEGIN
		PRINT 'YA SE ENCUENTRAN REGISTRADOS LOS DETALLES DE LOS PEDIDOS'
	END
	GO
GO

--CONSULTA
SELECT * FROM NORTHWND.DBO.[Order Details]
GO
SELECT * FROM BICICLETA.DBO.CLIENTES
GO

EXEC SP_IntertarDetallesOrdenes
GO


SELECT COUNT(1) FROM NORTHWND.DBO.Customers
GO
SELECT COUNT(1) FROM NORTHWND.DBO.Orders
GO
SELECT COUNT(1) FROM NORTHWND.DBO.[Order Details]
GO